# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [1]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
arr=np.random.randint(0, 21, (4, 7))
print('До нормализации:\n', arr, '\n')
normalized_arr = (arr-np.min(arr))/(np.max(arr)-np.min(arr))
print('После нормализации:\n',normalized_arr)

До нормализации:
 [[20 12  7  8  8 13  1]
 [ 9 13 15 15 14 19  9]
 [ 5 16 17 13 12  5  7]
 [ 4  7  1  7  8 14  2]] 

После нормализации:
 [[1.         0.57894737 0.31578947 0.36842105 0.36842105 0.63157895
  0.        ]
 [0.42105263 0.63157895 0.73684211 0.73684211 0.68421053 0.94736842
  0.42105263]
 [0.21052632 0.78947368 0.84210526 0.63157895 0.57894737 0.21052632
  0.31578947]
 [0.15789474 0.31578947 0.         0.31578947 0.36842105 0.68421053
  0.05263158]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import random
matr1=np.random.randint(0, 11, (8, 10))
print(matr1,'\n')
count=0

for i in range(len(matr1)):
  print(f'Сумма {i+1}-ой строки:',sum(matr1[i]))
res = matr1[np.argmin(np.sum(matr1, axis=1))]
res0=list(res)
for i in range(len(matr1)):
  if res0==list(matr1[i]):
    break
  else:
    count+=1
print(res, 'индекс строки - ', count)

[[ 0  7  5 10 10  7  6  1  5  4]
 [ 4  4  4  3  2  5  3  3  5  8]
 [ 8  3  9  3  6  9  6  2  4  6]
 [ 0  1  0  0  0  8  4  4  0 10]
 [ 0  3  2  3  2  0  3  8  3  8]
 [10 10  1 10  2  4  1 10  4  8]
 [ 0  4  6  0 10  7  8 10  5  0]
 [ 2  3  7  9  0  3  5  7  1  8]] 

Сумма 1-ой строки: 55
Сумма 2-ой строки: 41
Сумма 3-ой строки: 56
Сумма 4-ой строки: 27
Сумма 5-ой строки: 32
Сумма 6-ой строки: 60
Сумма 7-ой строки: 50
Сумма 8-ой строки: 45
[ 0  1  0  0  0  8  4  4  0 10] индекс строки -  3


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
point_1 = np.array((0, 0, 0))
point_2 = np.array((3, 3, 3))

distance = np.linalg.norm(point_1-point_2)
print(distance)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
from numpy import linalg as LA
A = np.array([[-1, 2, 4], [-3, 1, 2],[-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
B_inv = LA.inv(B)
D=np.dot(-1*C, B_inv)
print(np.linalg.solve(A,D))

[[ 1.00000000e+00  1.11022302e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
array = np.loadtxt('/content/minutes_n_ingredients.csv', delimiter=",", dtype='int32', skiprows=1)
array[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('2-ой столбец')
print('Минимум -', np.amin(array[:, 1]),
      'Максимум -', np.amax(array[:, 1]),
      'Медиана -', np.median(array[:, 1]),'\n')
print('3-ий столбец')
print('Минимум -', np.amin(array[:, 2]),
      'Максимум -', np.amax(array[:, 2]),
      'Медиана -', np.median(array[:, 2]),'\n')

2-ой столбец
Минимум - 0 Максимум - 2147483647 Медиана - 40.0 

3-ий столбец
Минимум - 1 Максимум - 39 Медиана - 9.0 



3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
quantile0=np.quantile(array[:, 1], 0.75)
print(array[array[:, 1]<=quantile0])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print('Количество рецептов, продолжительность которых - 0 минут: ',np.sum(array==0))
array[array==0]=1

Количество рецептов, продолжительность которых - 0 минут:  479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
print(f'Количество уникальных рецептов - {len(np.unique(array[:, 0]))}')

Количество уникальных рецептов - 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(f'Количество различных значений кол-ва ингредиентов - {len(np.unique(array[:, 2]))}, значения - {np.unique(array[:, 2])}')

Количество различных значений кол-ва ингредиентов - 37, значения - [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
new_array=[array[array[:, 2]<=5]]
print(new_array)

[array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
print('Максимальное значение -',np.amax(array[:,2]/array[:,1]))

Максимальное значение - 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
sorted_array=array[array[:, 1]. argsort()[::-1]]
print('Среднее кол-во ингредиентов -', np.average(sorted_array[:100,2]))

Среднее кол-во ингредиентов - 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
random=np.random.randint(array.shape[0],size=10)
print(array[random])

[[504914      1      7]
 [132505     25     11]
 [281185     90     10]
 [ 70322     20      7]
 [454880     45     19]
 [408907     30      8]
 [186058     35     10]
 [ 98954     75     27]
 [352545     37     13]
 [392389     55     16]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
new_array1=array[array[:, 2]<np.mean(array[:,2])]
print('Процент рецептов -', len(new_array1)/len(array)*100)

Процент рецептов - 58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [5]:
simple_numbers=np.full((100000,1), 0)
for i in range(len(array)):
  if array[i][1]<=20 and array[i][2]<=5:
    simple_numbers[i][0]=1

simple_array=np.append(array, simple_numbers, axis=1)
simple_array

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [6]:
print('Процент простых рецептов - ',len(simple_array[simple_array[:,3]==1])/len(array)*100)

Процент простых рецептов -  9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [31]:
group1 = array[array[:,1]<10]
group2 = array[np.logical_and(array[:,1]>=10, array[:,1]<20)]
group3 = array[array[:,1]>=20]
max_num = min(len(group1), len(group2), len(group3))
final_array = np.array([[group1[:max_num],group2[:max_num],group3[:max_num]]])
print(final_array)

[[[[ 67660      5      6]
   [366174      7      9]
   [204134      5      3]
   ...
   [420725      5      3]
   [  4747      0      9]
   [370915      5      4]]

  [[ 94746     10      6]
   [ 33941     18      9]
   [446597     15      5]
   ...
   [  9831     15      7]
   [335859     12     14]
   [256812     10      3]]

  [[127244     60     16]
   [ 23891     25      7]
   [157911     60     14]
   ...
   [168901     25      7]
   [392339     35     13]
   [206732     45     10]]]]
